# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170601_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zip',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
