# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_averageppw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageppw',
            name='installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Installer'),
        ),
    ]
