# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170605_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageppw',
            name='installer',
            field=models.CharField(max_length=200),
        ),
    ]
