# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170605_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicinstalls',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
