# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_historicinstalls_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicinstalls',
            name='counts',
        ),
    ]
