# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_historicinstalls_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicinstalls',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
