# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_historicinstalls_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AveragePPW',
        ),
        migrations.RenameField(
            model_name='installer',
            old_name='service_county',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='ac_size',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='dc_size',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='service_city',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='installer',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
